export const step1 = {
  images: [
    'step1_big_1.png',
    'step1_big_2.png',
    'step1_big_3.png',
    'step1_big_4.png',
    'step1_big_5.png',
    'step1_big_6.png',
    'step1_big_7.png',
    'step1_big_8.png',
    'step1_big_9.png',
    'step1_small_1.png',
    'step1_small_2.png',
    'step1_small_3.png',
    'step1_small_4.png',
    'step1_small_5.png',
    'step1_small_6.png',
    'step1_small_7.png',
    'step1_small_8.png',
    'step1_small_9.png',
    'step1_line_1.png',
    'step1_line_2.png',
    'step1_line_3.png',
    'step1_line_4.png',
    'step1_line_5.png',
    'step1_line_6.png',
    'step1_line_7.png',
    'step1_line_8.png',
    'step1_line_9.png',
    'step1_muck.png',
    //'step1_muck_outro.png',
    'step1_board_1.png',
    'step1_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step2 = {
  images: [
    'step2_big_1.png',
    'step2_big_2.png',
    'step2_big_3.png',
    'step2_big_4.png',
    'step2_big_5.png',
    'step2_big_6.png',
    'step2_big_7.png',
    'step2_big_8.png',
    'step2_big_9.png',
    'step2_small_1.png',
    'step2_small_2.png',
    'step2_small_3.png',
    'step2_small_4.png',
    'step2_small_5.png',
    'step2_small_6.png',
    'step2_small_7.png',
    'step2_small_8.png',
    'step2_small_9.png',
    'step2_line_1.png',
    'step2_line_2.png',
    'step2_line_3.png',
    'step2_line_4.png',
    'step2_line_5.png',
    'step2_line_6.png',
    'step2_line_7.png',
    'step2_line_8.png',
    'step2_line_9.png',
    'step2_muck.png',
    'step2_board_1.png',
    'step2_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step3 = {
  images: [
    'step3_big_1.png',
    'step3_big_2.png',
    'step3_big_3.png',
    'step3_big_4.png',
    'step3_big_5.png',
    'step3_big_6.png',
    'step3_big_7.png',
    'step3_big_8.png',
    'step3_big_9.png',
    'step3_small_1.png',
    'step3_small_2.png',
    'step3_small_3.png',
    'step3_small_4.png',
    'step3_small_5.png',
    'step3_small_6.png',
    'step3_small_7.png',
    'step3_small_8.png',
    'step3_small_9.png',
    'step3_line_1.png',
    'step3_line_2.png',
    'step3_line_3.png',
    'step3_line_4.png',
    'step3_line_5.png',
    'step3_line_6.png',
    'step3_line_7.png',
    'step3_line_8.png',
    'step3_line_9.png',
    'step3_muck.png',
    //'step3_muck_outro.png',
    'step3_board_1.png',
    'step3_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step4 = {
  images: [
    'step4_big_1.png',
    'step4_big_2.png',
    'step4_big_3.png',
    'step4_big_4.png',
    'step4_big_5.png',
    'step4_big_6.png',
    'step4_big_7.png',
    'step4_big_8.png',
    'step4_big_9.png',
    'step4_small_1.png',
    'step4_small_2.png',
    'step4_small_3.png',
    'step4_small_4.png',
    'step4_small_5.png',
    'step4_small_6.png',
    'step4_small_7.png',
    'step4_small_8.png',
    'step4_small_9.png',
    'step4_line_1.png',
    'step4_line_2.png',
    'step4_line_3.png',
    'step4_line_4.png',
    'step4_line_5.png',
    'step4_line_6.png',
    'step4_line_7.png',
    'step4_line_8.png',
    'step4_line_9.png',
    'step4_muck.png',
    //'step4_muck_outro.png',
    'step4_board_1.png',
    'step4_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step5 = {
  images: [
    'step5_big_1.png',
    'step5_big_2.png',
    'step5_big_3.png',
    'step5_big_4.png',
    'step5_big_5.png',
    'step5_big_6.png',
    'step5_big_7.png',
    'step5_big_8.png',
    'step5_big_9.png',
    'step5_small_1.png',
    'step5_small_2.png',
    'step5_small_3.png',
    'step5_small_4.png',
    'step5_small_5.png',
    'step5_small_6.png',
    'step5_small_7.png',
    'step5_small_8.png',
    'step5_small_9.png',
    'step5_line_1.png',
    'step5_line_2.png',
    'step5_line_3.png',
    'step5_line_4.png',
    'step5_line_5.png',
    'step5_line_6.png',
    'step5_line_7.png',
    'step5_line_8.png',
    'step5_line_9.png',
    'step5_muck.png',
    //'step5_muck_outro.png',
    'step5_board_1.png',
    'step5_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step6 = {
  images: [
    'step6_big_1.png',
    'step6_big_2.png',
    'step6_big_3.png',
    'step6_big_4.png',
    'step6_big_5.png',
    'step6_big_6.png',
    'step6_big_7.png',
    'step6_big_8.png',
    'step6_big_9.png',
    'step6_small_1.png',
    'step6_small_2.png',
    'step6_small_3.png',
    'step6_small_4.png',
    'step6_small_5.png',
    'step6_small_6.png',
    'step6_small_7.png',
    'step6_small_8.png',
    'step6_small_9.png',
    'step6_line_1.png',
    'step6_line_2.png',
    'step6_line_3.png',
    'step6_line_4.png',
    'step6_line_5.png',
    'step6_line_6.png',
    'step6_line_7.png',
    'step6_line_8.png',
    'step6_line_9.png',
    'step6_muck.png',
    //'step6_muck_outro.png',
    'step6_board_1.png',
    'step6_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step7 = {
  images: [
    'step7_big_1.png',
    'step7_big_2.png',
    'step7_big_3.png',
    'step7_big_4.png',
    'step7_big_5.png',
    'step7_big_6.png',
    'step7_big_7.png',
    'step7_big_8.png',
    'step7_big_9.png',
    'step7_small_1.png',
    'step7_small_2.png',
    'step7_small_3.png',
    'step7_small_4.png',
    'step7_small_5.png',
    'step7_small_6.png',
    'step7_small_7.png',
    'step7_small_8.png',
    'step7_small_9.png',
    'step7_line_1.png',
    'step7_line_2.png',
    'step7_line_3.png',
    'step7_line_4.png',
    'step7_line_5.png',
    'step7_line_6.png',
    'step7_line_7.png',
    'step7_line_8.png',
    'step7_line_9.png',
    'step7_muck.png',
    //'step7_muck_outro.png',
    'step7_board_1.png',
    'step7_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step8 = {
  images: [
    'step8_big_1.png',
    'step8_big_2.png',
    'step8_big_3.png',
    'step8_big_4.png',
    'step8_big_5.png',
    'step8_big_6.png',
    'step8_big_7.png',
    'step8_big_8.png',
    'step8_big_9.png',
    'step8_small_1.png',
    'step8_small_2.png',
    'step8_small_3.png',
    'step8_small_4.png',
    'step8_small_5.png',
    'step8_small_6.png',
    'step8_small_7.png',
    'step8_small_8.png',
    'step8_small_9.png',
    'step8_line_1.png',
    'step8_line_2.png',
    'step8_line_3.png',
    'step8_line_4.png',
    'step8_line_5.png',
    'step8_line_6.png',
    'step8_line_7.png',
    'step8_line_8.png',
    'step8_line_9.png',
    'step8_muck.png',
    //'step8_muck_outro.png',
    'step8_board_1.png',
    'step8_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step9 = {
  images: [
    'step9_big_1.png',
    'step9_big_2.png',
    'step9_big_3.png',
    'step9_big_4.png',
    'step9_big_5.png',
    'step9_big_6.png',
    'step9_big_7.png',
    'step9_big_8.png',
    'step9_big_9.png',
    'step9_small_1.png',
    'step9_small_2.png',
    'step9_small_3.png',
    'step9_small_4.png',
    'step9_small_5.png',
    'step9_small_6.png',
    'step9_small_7.png',
    'step9_small_8.png',
    'step9_small_9.png',
    'step9_line_1.png',
    'step9_line_2.png',
    'step9_line_3.png',
    'step9_line_4.png',
    'step9_line_5.png',
    'step9_line_6.png',
    'step9_line_7.png',
    'step9_line_8.png',
    'step9_line_9.png',
    'step9_muck.png',
    //'step9_muck_outro.png',
    'step9_board_1.png',
    'step9_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step10 = {
  images: [
    'step10_big_1.png',
    'step10_big_2.png',
    'step10_big_3.png',
    'step10_big_4.png',
    'step10_big_5.png',
    'step10_big_6.png',
    'step10_big_7.png',
    'step10_big_8.png',
    'step10_big_9.png',
    'step10_small_1.png',
    'step10_small_2.png',
    'step10_small_3.png',
    'step10_small_4.png',
    'step10_small_5.png',
    'step10_small_6.png',
    'step10_small_7.png',
    'step10_small_8.png',
    'step10_small_9.png',
    'step10_line_1.png',
    'step10_line_2.png',
    'step10_line_3.png',
    'step10_line_4.png',
    'step10_line_5.png',
    'step10_line_6.png',
    'step10_line_7.png',
    'step10_line_8.png',
    'step10_line_9.png',
    'step10_muck.png',
    //'step10_muck_outro.png',
    'step10_board_1.png',
    'step10_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step11 = {
  images: [
    'step11_big_1.png',
    'step11_big_2.png',
    'step11_big_3.png',
    'step11_big_4.png',
    'step11_big_5.png',
    'step11_big_6.png',
    'step11_big_7.png',
    'step11_big_8.png',
    'step11_big_9.png',
    'step11_small_1.png',
    'step11_small_2.png',
    'step11_small_3.png',
    'step11_small_4.png',
    'step11_small_5.png',
    'step11_small_6.png',
    'step11_small_7.png',
    'step11_small_8.png',
    'step11_small_9.png',
    'step11_line_1.png',
    'step11_line_2.png',
    'step11_line_3.png',
    'step11_line_4.png',
    'step11_line_5.png',
    'step11_line_6.png',
    'step11_line_7.png',
    'step11_line_8.png',
    'step11_line_9.png',
    'step11_muck.png',
    //'step11_muck_outro.png',
    'step11_board_1.png',
    'step11_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step12 = {
  images: [
    'step12_big_1.png',
    'step12_big_2.png',
    'step12_big_3.png',
    'step12_big_4.png',
    'step12_big_5.png',
    'step12_big_6.png',
    'step12_big_7.png',
    'step12_big_8.png',
    'step12_big_9.png',
    'step12_small_1.png',
    'step12_small_2.png',
    'step12_small_3.png',
    'step12_small_4.png',
    'step12_small_5.png',
    'step12_small_6.png',
    'step12_small_7.png',
    'step12_small_8.png',
    'step12_small_9.png',
    'step12_line_1.png',
    'step12_line_2.png',
    'step12_line_3.png',
    'step12_line_4.png',
    'step12_line_5.png',
    'step12_line_6.png',
    'step12_line_7.png',
    'step12_line_8.png',
    'step12_line_9.png',
    'step12_muck.png',
    //'step12_muck_outro.png',
    'step12_board_1.png',
    'step12_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step13 = {
  images: [
    'step13_big_1.png',
    'step13_big_2.png',
    'step13_big_3.png',
    'step13_big_4.png',
    'step13_big_5.png',
    'step13_big_6.png',
    'step13_big_7.png',
    'step13_big_8.png',
    'step13_big_9.png',
    'step13_small_1.png',
    'step13_small_2.png',
    'step13_small_3.png',
    'step13_small_4.png',
    'step13_small_5.png',
    'step13_small_6.png',
    'step13_small_7.png',
    'step13_small_8.png',
    'step13_small_9.png',
    'step13_line_1.png',
    'step13_line_2.png',
    'step13_line_3.png',
    'step13_line_4.png',
    'step13_line_5.png',
    'step13_line_6.png',
    'step13_line_7.png',
    'step13_line_8.png',
    'step13_line_9.png',
    'step13_muck.png',
    //'step13_muck_outro.png',
    'step13_board_1.png',
    'step13_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step14 = {
  images: [
    'step14_big_1.png',
    'step14_big_2.png',
    'step14_big_3.png',
    'step14_big_4.png',
    'step14_big_5.png',
    'step14_big_6.png',
    'step14_big_7.png',
    'step14_big_8.png',
    'step14_big_9.png',
    'step14_small_1.png',
    'step14_small_2.png',
    'step14_small_3.png',
    'step14_small_4.png',
    'step14_small_5.png',
    'step14_small_6.png',
    'step14_small_7.png',
    'step14_small_8.png',
    'step14_small_9.png',
    'step14_line_1.png',
    'step14_line_2.png',
    'step14_line_3.png',
    'step14_line_4.png',
    'step14_line_5.png',
    'step14_line_6.png',
    'step14_line_7.png',
    'step14_line_8.png',
    'step14_line_9.png',
    'step14_muck.png',
    //'step14_muck_outro.png',
    'step14_board_1.png',
    'step14_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}

export const step15 = {
  images: [
    'step15_big_1.png',
    'step15_big_2.png',
    'step15_big_3.png',
    'step15_big_4.png',
    'step15_big_5.png',
    'step15_big_6.png',
    'step15_big_7.png',
    'step15_big_8.png',
    'step15_big_9.png',
    'step15_small_1.png',
    'step15_small_2.png',
    'step15_small_3.png',
    'step15_small_4.png',
    'step15_small_5.png',
    'step15_small_6.png',
    'step15_small_7.png',
    'step15_small_8.png',
    'step15_small_9.png',
    'step15_line_1.png',
    'step15_line_2.png',
    'step15_line_3.png',
    'step15_line_4.png',
    'step15_line_5.png',
    'step15_line_6.png',
    'step15_line_7.png',
    'step15_line_8.png',
    'step15_line_9.png',
    'step15_muck.png',
    //'step15_muck_outro.png',
    'step15_board_1.png',
    'step15_board_2.png'
  ],
  sounds: [],
  json: [],
  videos: [],
  spine: []
}
